/*
Projeto Mathematical Ramblings (mathematicalramblings.blogspot.com).

Script Maxima de conversão de um complexo na forma algébrica para trigonométrica.
*/

print ("Projeto Mathematical Ramblings (mathematicalramblings.blogspot.com).");

print ("Script Maxima de conversão de um complexo na forma algébrica para trigonométrica.");

z: read ("Entre com o complexo:");

print ("Módulo: ", abs (z));

print ("Argumento: ", carg (z));

kill (z);