/*
Projeto Mathematical Ramblings (mathematicalramblings.blogspot.com).

Script Maxima para cálculo da hipotenusa de um triângulo retângulo.
*/

print ("Projeto Mathematical Ramblings (mathematicalramblings.blogspot.com).");

print ("Script Maxima para cálculo da hipotenusa de um triângulo retângulo.");

b: read("Entre com o valor de um cateto:");

c: read("Entre com o valor do outro cateto:");

print ("A hipotenusa é ", sqrt(b^2 + c^2));

kill (b, c);