/*
Projeto Mathematical Ramblings (http://bit.ly/mathematicalramblings).

Script Maxima de conversão de um complexo na forma algébrica para trigonométrica.
*/

print ("Projeto Mathematical Ramblings (http://bit.ly/mathematicalramblings).");

print ("Script Maxima de conversão de um complexo na forma algébrica para trigonométrica.");

z: read ("Entre com o complexo:");

print ("Módulo: ", abs (z));

print ("Argumento: ", carg (z));

kill (z);